### ISSUE TITLE
Docker-compose

### ISSUE THREAD

**Issue by ElenaBorgo** [ElenaBorgo/Diploma-qa-47#2]
1.  Я запустила приложение - ура!
2. Подключилась к виртуальной машине, создала контейнер, ввожу docker-compose up - ошибка: занят порт. Я вообще там docker-compose up пишу или надо в idea? И как избежать этой ошибки, не исправляя везде порт 3306?
![Screenshot_64](https://user-images.githubusercontent.com/114416092/225576577-1c1dbf14-0c17-4a8b-9a67-0f2ce14abf52.png)
3. Как подключить машину к idea? Прописала везде ip адрес, но контейнеров не видно. Или не должно быть видно?  Надо что-то в настройках плагина писать или нет?
![Screenshot_63](https://user-images.githubusercontent.com/114416092/225577316-0a56e120-49aa-4fdb-8436-480777f2ed7e.png)
![Screenshot_65](https://user-images.githubusercontent.com/114416092/225577334-e23221c4-0182-4776-8e86-e3e4c00872cf.png)
![Screenshot_61](https://user-images.githubusercontent.com/114416092/225577720-3970f30a-75fc-4933-9f8f-bf3df0f8d26c.jpg)
![Screenshot_69](https://user-images.githubusercontent.com/114416092/225585833-1a1c0909-f420-408b-88d1-69ce14ae3ce3.png)

4. О симуляторе. Его запускать надо в PuTTy или в идее? Я добавила каталог в проект и dockerfile тоже. Пыталась запустить через идею. Через PaTTy запускаю, говорит спросить у администратора 
![Screenshot_66](https://user-images.githubusercontent.com/114416092/225582769-9bcbff57-02c3-4232-873d-336cc478d336.png)
![Screenshot_68](https://user-images.githubusercontent.com/114416092/225585485-10130c37-af0b-4767-a18a-fd0df1e003d6.png)

**Comment by ArRomanov** [comment]
1. Ошибка из-за того, что уже есть запущенные контейнеры, работающие на этих портах. Вам нужно следить, чтобы в одно время работало по одному контейнеру для Mysql, Postgres и для Node. Перед запуском контейнеров нужно убедиться, что другие контейнеры не запущены, а если запущены, то остановить и удалить их. Все контейнеры в системе можно посмотреть командой `docker ps -a`
2. В ide вы контейнеров не увидите, их статусы можно проверять только на виртуальной машине, так как виртуальная машина и ваш ПК никак между собой не связаны. Единственный доступ к контейнерам с вашего ПК - ip виртуальной машины + порт. Таким образом вы можете подключаться к базе данных и к gate-simulator, для этого вместо localhost в конфигурации просто указываете ip вашей виртуальной машины
3. gate-simulator так же запускается в контейнере на виртуальной машине. У вас должен быть корректный Dockerfile и в общем docker-compose.yml инструкция по запуску контейнера (все это есть в примере, который я вам присылал в дискорд). Все описанные в docker-compose.yml сервисы будут запускаться одной командой `docker-compose up` или `docker-compose up -d`, дополнительно запускать ничего не нужно

**Comment by ElenaBorgo** [comment]
Не находит какие-то файлы и директории. Что то нужно дописать в Dockerfile. Пробовала менять названия папок в WORKDIR и COPY. Если просто скопировать с файла, который вы прислали, сборка падает. И docker-compose.yml дописала, но все без толку. Как вообще понять, что Dockerfile корректный? Мы это не проходили. Я погуглила, так поняла, что директории должны автоматически создаваться.  Скопировала сначала Dockerfile в папку gate-simulator, но так вообще ничего не находит, переместила в корень проекта.

![Screenshot_74](https://user-images.githubusercontent.com/114416092/226096940-82077034-69d2-4aa8-961f-4ee4b191ea85.png)
![Screenshot_75](https://user-images.githubusercontent.com/114416092/226096943-5a917674-3930-44d5-8739-bf12ef39f009.png)
![Screenshot_76](https://user-images.githubusercontent.com/114416092/226096945-d27e0701-8f33-465e-b99e-31d45167ec5e.png)

**Comment by ArRomanov** [comment]
Dockerfile копируйте из примера, но расположить его нужно в директории gate-simulator. А в docker-compose.yml в пункте build указать путь до Dockerfile - вместо точки написать `gate-simulator`
