### ISSUE TITLE
gate-simulator

### ISSUE THREAD

**Issue by ElenaBorgo** [ElenaBorgo/Diploma-qa-47#3]
1. Я сделала необходимые поправки в docker-compose.yml. Теперь, при попытке запустить контейнеры, красным сообщается что старая версия lockfile. Я пытаюсь ввести команду, которую мне подсказывает в терминале, но не выходит, так как нет прав администратора. 
![Screenshot_78](https://user-images.githubusercontent.com/114416092/227700248-61ce2e03-346d-487f-a8fd-97d492502627.png)
![Screenshot_79](https://user-images.githubusercontent.com/114416092/227700261-0bf2cf76-f0b7-48a7-8cc3-0f63fbd390e0.png)
 2. Пробовала поменять версию lockerfile с 1 на 2 в package-lock.json, тоже самое: 
![Screenshot_80](https://user-images.githubusercontent.com/114416092/227701686-fe4569d3-eed0-4622-b36d-31d1d03ac787.png)

**Comment by ArRomanov** [comment]
у вас опечатка в названии файла [packege.json](https://github.com/ElenaBorgo/Diploma-qa-47/blob/main/gate-simulator/packege.json). В логах ошибка "no such file or directory, open /opt/app/package.json"

**Comment by ElenaBorgo** [comment]
1. Наконец-то контейнеры запустились!
2. Я так понимаю, мне не нужно создавать новые таблицы пользователей и карт? А если нужно, то я создала, и не могу найти теперь.
![Снимок экрана (67)](https://user-images.githubusercontent.com/114416092/227967408-7752b95c-2b8d-4f27-8ac3-053fe7a82d78.jpg)
3. Пытаюсь писать UI-тесты, но у меня не загружается Selenide. Пишет, что нужно загрузить библиотеку, но ничего не происходит. Пробовала разные версии Selenide. 
![Screenshot_82](https://user-images.githubusercontent.com/114416092/227967219-3783e71c-e73a-44c4-afbe-ec145654b9cb.png)

**Comment by ArRomanov** [comment]
1. Таблицы создавать не нужно и вручную заполнять тоже ничего не нужно. Пользователь БД у вас создается при создании БД (вся конфигурация прописана в docker-compose.yml), а для приложения пользователь вообще не нужен, авторизации в приложении нет. После успешного запуска приложения у вас должно появиться три таблицы, ищите их в schemas->app->tables
2. Код лучше хранить не в src/main/java а в src/test/java, это во-первых. А во-вторых, зависимости в build.gradle лучше подключать через **implementation** вместо **testImplementation**. В первом варианте подключенная зависимость будет доступна и в src/main/java и в src/test/java, а во втором случае только в src/test/java, что у вас сейчас и происходит
![image](https://user-images.githubusercontent.com/23121947/228017437-36fce746-2512-49d3-a46a-ad4fac2f97c3.png)
