### ISSUE TITLE
DataHelper

### ISSUE THREAD

**Issue by ElenaBorgo** [ElenaBorgo/Diploma-qa-47#4]
1. Я набросала DataHelper. Нужно ли мне разграничивать данные карт(месяц, год, владелец) на валидные и невалидные? Если нужно, то как их объединить в один метод(например только с валидными данными), если это разные типы данных? В другом случае, если написать отдельные статические классы(как у меня сейчас), и после этого еще написать отдельные методы и к ним конструктор, не будет ли код излишним?
2. Как мне сослаться на методы из DataHelper, если их слишком много?

**Comment by ArRomanov** [comment]
1. В DataHelper удалите все вложенные классы, с одним полем эти классы излишне, просто в методе возвращайте строковое или числовое значение и используйте там, где нужно. Для получения года и месяца можно написать по одному методу, который будет принимать числовой параметр и прибавлять его к текущему году/месяцу (или отнимать). Таким образом вы сможете получить прошлый, настоящий и будущий год/месяц. По поводу остальных данных можете сделать отдельно методы для валидных и невалидных данных 
[1 ссылка](https://beginnersbook.com/2017/11/java-8-adding-days-to-the-localdate/) - пример как сдвинуть текущую дату на день
[2 ссылка](https://stackoverflow.com/questions/28177370/how-to-format-localdate-to-string) - пример приведения даты к нужному формату
[3 ссылка](https://divancoder.ru/2017/12/simpledateformat/) - шаблоны форматирования даты в java
2. Этот вопрос не совсем понятен, что значит сослаться на методы?

**Comment by ElenaBorgo** [comment]
1.  Посмотрите в DashboardPage я написала методы, где надо нажать на кнопки купить или купить в кредит. Там почему-то ошибка при переходе в новый класс. Нужен ли вообще отдельный DashboardPage для перехода, скажем, на PaymentPage?
![Screenshot_85](https://user-images.githubusercontent.com/114416092/228805493-9bc643bf-f163-4ba9-be68-960674ad60a9.png)
2. При вводе в поле номер карты с негативным сценарием (declined), у меня все равно появляется сообщение об успешной операции. Видимо, нужно как-то подключаться к симулятору (npm start)? Но я не знаю в каком терминале это писать. Пишу в Patty - ничего не происходит, в идее - показывает ошибку.
![Снимок экрана (70)](https://user-images.githubusercontent.com/114416092/228804790-8e9856be-e2ba-4cde-bc8c-4c2b377459cf.png)
![Screenshot_84](https://user-images.githubusercontent.com/114416092/228804850-00107a65-dae9-4e8e-97c5-310d42426599.png)
3. Про негативные сценарии. Например, я написала метод где все данные невалидные. Нужно ли мне писать метод, где номер карты для отклонения операции(declined), а другие данные валидные(месяц, год)? И наоборот, номер карты для успешной операции, а год и месяц неправильные?

**Comment by ArRomanov** [comment]
1. Да, второй класс страницы с формой стоит сделать. Только в методах достаточно будет сделать `return new FormPage();`
2. Кажется, что это баг. Если остальные три оплаты (второй картой на этой форме и двумя картами на другой) происходят с корректными сообщениями, значит ваше приложение запущено корректно. Там точно был один баг с неправильным сообщением, но я не помню с какой картой и на какой форме
3. Смотря, что вы проверяете. Если пустые поля, то без разницы - форма с пустыми полями не должна отправиться. Если проверяете любые поля, кроме карты, то номер карты можете писать любой. Если хотите проверить невалидный номер карты, то остальные поля пишите валидными. Можно по-разному комбинировать все проверки, попробуйте сначала на черновике расписать список проверок и потом реализовать, хотя у вас в плане это примерно должно быть

**Comment by ElenaBorgo** [comment]
1. Кажется все-таки неправильно запущено приложение: я проверила все 4 варианта(обе карты, обе формы) и все они прошли успешно, ни одного сообщения об ошибке. Есть скриншоты, если надо скину, но там ничего информативного.
2. Написала один тестик, он не проходит, не открывается url. Появляется пустая страница браузера. Может в билд гредл что-то неправильно.
![Снимок экрана (72)](https://user-images.githubusercontent.com/114416092/229112257-c9bb56ef-db58-4881-9cdc-5d085abf3146.png)
![Снимок экрана (71)](https://user-images.githubusercontent.com/114416092/229112275-03d78c52-dae1-4ced-a6d9-542d73abeac4.png)
![Screenshot_83](https://user-images.githubusercontent.com/114416092/229112355-4a364aed-3fc9-4c0e-b45b-1edca8ed5075.png)
![Screenshot_86](https://user-images.githubusercontent.com/114416092/229112368-affdd72e-b758-46e0-94fd-3d4d0beaff39.png)
![Screenshot_87](https://user-images.githubusercontent.com/114416092/229112384-0a03558b-1f93-424c-9906-87732e85f887.png)
![Screenshot_84](https://user-images.githubusercontent.com/114416092/229112880-e1b079db-07e6-4bf4-834a-5b5e0ff01e6d.png)
