### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by ElenaBorgo** [ElenaBorgo/Diploma-qa-47#5]
1. При запуске тестов все прогружается, страница в браузере открывается, все вроде норм. С другой стороны, один раз у меня оборвалось соединение с машиной, но тесты все равно прошли. И карты все с успешным исходом все равно. Мне надо тесты писать, где expected -  это появление сообщения об ошибке, а actual - об успехе? В этом смысл?
2.  Посмотрите, пожалуйста, тесты. Я там в комментариях написала вопросы. Если вам так неудобно, я их здесь оформлю. В задании написано, что можно прямо в коде писать.

**Comment by ArRomanov** [comment]
1. Если вы проверяете элементы интерфейса страницы, то проверки у вас будут следующего типа
`successNotification.shouldBe(visible, Duration.ofSeconds(15))`, что означает элемент successNotification должен стать видимым в течение 15 секунд. Фактический результат (actual) - состояние элемента в данный момент, ожидаемый результат (expected) - элемент видимый. Когда будете проверять информацию в бд, то, например, получаете из бд значение поля status последней транзакции и сравниваете через обычный assert с ожидаемым - `assertEquals("APPROVED", status)`. По селенид посмотрите еще раз примеры с лекции https://github.com/netology-code/aqa-code/tree/master/selenide/selenide, а работа с БД тут https://github.com/netology-code/aqa-code/tree/master/sql

по коду сейчас посмотрю и отвечу отдельным комментарием

**Comment by ArRomanov** [comment]
> //        var expected  = approvedPayment.successTransaction();
//        var actual = ?
//       Например, я написала ожидаемый результат - это метод successTransaction(), но что писать в актуальном? И нужны
//       ли в этом тесте ассерты?

Достаточно просто вызова `approvedPayment.successTransaction();`, он вполне может быть void, из него необязательно что-то получать. Как это работает описал выше. Еще его стоит переименовать, добавив префикс check - `approvedPayment.checkSuccessfulTransaction();`. Вообще, во всех методах в качестве префикса должен стоять глагол, показывающий действие данного метода

> //    Я создала метод, где пользователь вводит неправильный месяц. Метод типа void. Я не могу его использовать в тесте
//    из-за этого. Какого типа он должен быть, чтобы я смогла его вызвать? Static не получается. Я не хочу для него
//    отдельный класс создавать.

Если у вас метод void, то вы просто не получаете из него никаких значений, просто вызываете `paymentPage.makeTransactionWithInvalidMonth();` и действие на странице будет выполнено. Метод не обязательно должен что-то вернуть, он может просто выполнить действие и все, а следующий метод у вас будет проверять наличие какого-то элемента на странице, например

> //    Здесь не проходят ассерты. Во-первых, пришлось в методе errorTransaction(), сообщение сделать hidden, потому что оно не появляется.
//    Во-вторых, что писать в актуальном результате? Так как у меня одобренный и отклоненный кредит в разных классах, я не могу
//    в actual привести другой класс.

Если уведомление об ошибке не появилось, но должно, а вместо него появилось другое - это баг. Тест должен проверять в соответствии с требованиями и в случае несоответствии реализации требованиям проверяющий тест должен "упасть". Про актуальный результат уже выше пояснил

Вообще, настоятельно рекомендую пересмотреть лекции по автоматизации тестирования интерфейса (3 selenium, 4 selenide) и вы получите ответы на все базовые вопросы, которые мне задаете

**Comment by ElenaBorgo** [comment]
С чего вы взяли, что я не смотрела предыдущие лекции?? Я у вас спрашиваю, когда не могу прийти сама к ответу, если бы я смогла получить ответы сама, не спрашивала бы
